name: Realtor Omaha Nebraska Troy Granger
favicon: null
layout_spectrum: 0.22819124511443079
typography_spectrum: 0.6848097804468125
title: Real Estate Omaha Nebraska
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3992988851387054
  lightness: 0.45351617713458836
  saturation: 0.03505503409542143
  rhythmicContrast: 0.5848453734070063
purpose: []
