name: Realtor Omaha Nebraska Troy Granger
favicon: null
layout_spectrum: 0.51075
typography_spectrum: 0.25435
title: Real Estate Omaha Nebraska
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#062a5e'
    - '#6a9a13'
    - '#b5bfd0'
    - '#445b84'
  brandStrength: 0.875
  lightness: 0.45351617713458836
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
